### ISSUE TITLE
MFT 6: System freezes when a card number of 3 is inserted

### ISSUE THREAD

**Issue by bryson189** [enochtsang/seng437-assignment1#18]
Function Being Tested: System rejects an unreadable card 

------------

Build Number: Version Number 1.0

Reported On: 26/01/16

Description:
The system freezes after a card number of 3 is entered and a random PIN is entered.

Steps To Reproduce:
1) Run ATM system version 1.0
2) Turn the system on by pressing the "ON" button
3) Enter 10 for the the number of $20 bills 
4) Click “Click to insert card”
5) Input 3 as the card number
6) Input any number as the PIN number and click “ENTER”

------------

Expected result:
Card is ejected; System displays an error screen; System is ready to start a new session

**Comment by kkcmah** [comment]
Resolved: This issue has been fixed in version 1.1.
