### ISSUE TITLE
ET: System withdraws an amount that is more than what the user has requested

### ISSUE THREAD

**Issue by jqvillar** [enochtsang/seng437-assignment1#2]
Function Being Tested: Withdrawal

------------

Build Number: Version Number 1.0

Reported On: 24/01/16 

Description:
The system does not withdraw the correct amount that the user chose. The system withdraws more than the amount chosen.

Steps To Reproduce:
1) ATM Machine must be turned “ON”
2) Enter 20 for the the number of $20 bills 
3) Click “Click to insert card”
4) Input 2 as the card number
5) Input 1234 as the PIN number and click “ENTER”
6) Press 1 to choose the “Withdraw” option
7) Press 3 to choose “MONEY MARKET”
8) Choose any amount to withdraw by pressing 1,2, or 3 ( to withdraw $20, $40, or $60 )

------------
Expected result:
The system withdraws the correct amount chosen  by the user; The system displays the correct amount and updated balance; The system correctly records the transaction in the log (this includes the request to the bank and the bank approval)

**Comment by bryson189** [comment]
This issue has been fixed in version 1.1.
